// Fleet Data parsed from YELLOWBOX OB .csv
const fleetData = {
    riders:     [
        {
            "id": 1,
            "name": "Muhammad Muzammal Fareed Muhammad Aslam",
            "talabatId": "2504631",
            "keetaId": "",
            "zone": "Jumeirah",
            "bike": "52379 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "542007958",
            "email": "fareed.yb52397@gmail.com",
            "joiningDate": "12-24-2024",
            "status": "active"
        },
        {
            "id": 2,
            "name": "Judge Singh Chanan Singh",
            "talabatId": "2504643",
            "keetaId": "",
            "zone": "Business bay",
            "bike": "53885 DXB 2",
            "nationality": "Indian",
            "cPhone": "542007942",
            "email": "judge.yb53885@gmail.com",
            "joiningDate": "12-24-2024",
            "status": "active"
        },
        {
            "id": 3,
            "name": "Mashkoor Hussain Tawaseen",
            "talabatId": "1353588",
            "keetaId": "",
            "zone": "Al barsha 1",
            "bike": "53886 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "542007947",
            "email": "mashkoor.yb53886@gmail.com",
            "joiningDate": "12-24-2024",
            "status": "active"
        },
        {
            "id": 4,
            "name": "Siraj Mannil Kunhimohamed",
            "talabatId": "2504613",
            "keetaId": "",
            "zone": "Deira",
            "bike": "53889 DXB 2",
            "nationality": "Indian",
            "cPhone": "542007957",
            "email": "siraj.yb53889@gmail.com",
            "joiningDate": "12-24-2024",
            "status": "offboarded"
        },
        {
            "id": 5,
            "name": "Jatinder Singh Balbir Singh",
            "talabatId": "2504612",
            "keetaId": "1760641953580910",
            "zone": "Deira",
            "bike": "53890 DXB 2",
            "nationality": "Indian",
            "cPhone": "542007943",
            "email": "jatinder.yb53890@gmail.com",
            "joiningDate": "12-24-2024",
            "status": "active"
        },
        {
            "id": 6,
            "name": "Sayed Raheel Kazmi Sayed Tanveer Hussain Kazmi",
            "talabatId": "2504608",
            "keetaId": "",
            "zone": "Business bay",
            "bike": "54940 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "542007950",
            "email": "raheel.yb54940@gmail.com",
            "joiningDate": "12-24-2024",
            "status": "active"
        },
        {
            "id": 7,
            "name": "Faiz Ahmad Khan Faizan Ahmad Khan",
            "talabatId": "2508895",
            "keetaId": "1758799355593264",
            "zone": "Jumeirah",
            "bike": "53891 DXB 2",
            "nationality": "Indian",
            "cPhone": "542007953",
            "email": "faiz.yb53891@gmail.com",
            "joiningDate": "12-24-2024",
            "status": "keeta"
        },
        {
            "id": 8,
            "name": "Muhammad Muneeb Ur Rehman Saghir Ahmed",
            "talabatId": "1966331",
            "keetaId": "",
            "zone": "Downtown",
            "bike": "53892 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "542201174",
            "email": "muneed.yb53892@gmail.com",
            "joiningDate": "1-9-2025",
            "status": "offboarded"
        },
        {
            "id": 9,
            "name": "RanJit Singh Babu Singh",
            "talabatId": "1386308",
            "keetaId": "",
            "zone": "Downtown",
            "bike": "54938 DXB 2",
            "nationality": "Indian",
            "cPhone": "542201157",
            "email": "ranjit.yb54938@gmail.com",
            "joiningDate": "01-14-2025",
            "status": "active"
        },
        {
            "id": 10,
            "name": "Waqar Naeem Abdul Ghaffar",
            "talabatId": "2544281",
            "keetaId": "",
            "zone": "Downtown",
            "bike": "54939 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "542201179",
            "email": "waqar.yb54939@gmail.com",
            "joiningDate": "01-18-2025",
            "status": "active"
        },
        {
            "id": 11,
            "name": "Sakil Ahmed Md Showkot Ali",
            "talabatId": "1732897",
            "keetaId": "",
            "zone": "Al barsha 1",
            "bike": "54941 DXB 2",
            "nationality": "Bangladeshi",
            "cPhone": "542201172",
            "email": "sakil.yb54941@gmail.com",
            "joiningDate": "01-22-2025",
            "status": "active"
        },
        {
            "id": 12,
            "name": "Husnain Bahadar Khan",
            "talabatId": "1834259",
            "keetaId": "",
            "zone": "Al Satowa",
            "bike": "54943 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "542201169",
            "email": "husnain.yb54943@gmail.com",
            "joiningDate": "01-23-2025",
            "status": "offboarded"
        },
        {
            "id": 13,
            "name": "Pawan Bharati Narjit Bharati",
            "talabatId": "2637842",
            "keetaId": "",
            "zone": "Al karama",
            "bike": "54942 DXB 2",
            "nationality": "Nepal",
            "cPhone": "542201182",
            "email": "pawan.yb54942@gmail.com",
            "joiningDate": "02-DD-YYYY",
            "status": "active"
        },
        {
            "id": 14,
            "name": "Safdar Muhammad Iqbal",
            "talabatId": "2650502",
            "keetaId": "",
            "zone": "Al barsha 1",
            "bike": "54947 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "504084814",
            "email": "safdar.yb54947@gmail.com",
            "joiningDate": "02-DD-YYYY",
            "status": "active"
        },
        {
            "id": 15,
            "name": "Md Ashfaque Raja Md Mansur Alam",
            "talabatId": "2663590",
            "keetaId": "",
            "zone": "Marina",
            "bike": "55970 DXB 2",
            "nationality": "Indian",
            "cPhone": "504084398",
            "email": "ashfaque.yb55970@gmail.com",
            "joiningDate": "02-DD-YYYY",
            "status": "offboarded"
        },
        {
            "id": 16,
            "name": "Abdul Raheem Mohammed Abdul Aleem",
            "talabatId": "2663587",
            "keetaId": "",
            "zone": "Marina",
            "bike": "55971 DXB 2",
            "nationality": "Indian",
            "cPhone": "50408439",
            "email": "raheem.yb55971@gmail.com",
            "joiningDate": "02-DD-YYYY",
            "status": "offboarded"
        },
        {
            "id": 17,
            "name": "Muhammad Sanwal Kharal Munir Ahmad",
            "talabatId": "1119038",
            "keetaId": "1758808037593624",
            "zone": "Marina",
            "bike": "55706 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "504082038",
            "email": "sanwal.yb55706@gmail.com",
            "joiningDate": "03-DD-YYYY",
            "status": "offboarded"
        },
        {
            "id": 18,
            "name": "Md Danish Khan",
            "talabatId": "2813427",
            "keetaId": "1758809174580041",
            "zone": "Al Quoz",
            "bike": "55426 DXB 2",
            "nationality": "Nepal",
            "cPhone": "551288147",
            "email": "danish.yb55426@gmail.com",
            "joiningDate": "03-DD-YYYY",
            "status": "keeta"
        },
        {
            "id": 19,
            "name": "Mohammad Shuaib Moazzam Naimi Mohammad Moazzam Naimi",
            "talabatId": "2815064",
            "keetaId": "1760792017512260",
            "zone": "Al Wasal",
            "bike": "55964 DXB 2",
            "nationality": "Indian",
            "cPhone": "504089166",
            "email": "shuaib.yb55964@gmail.com",
            "joiningDate": "03-DD-YYYY",
            "status": "active"
        },
        {
            "id": 20,
            "name": "Nazim Ali Feroz Khan",
            "talabatId": "1506153",
            "keetaId": "1757922904593574",
            "zone": "Al Satowa",
            "bike": "55429 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "503747106",
            "email": "nazim.yb55429@gmail.com",
            "joiningDate": "03-15-2025",
            "status": "keeta"
        },
        {
            "id": 21,
            "name": "Hassan Nabil Hassan Mohamed Fekry",
            "talabatId": "2825233",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55647 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "504089511",
            "email": "hassan.yb55647@gmail.com",
            "joiningDate": "03-15-2025",
            "status": "offboarded"
        },
        {
            "id": 22,
            "name": "Mohamed Manal Abdelsalam Ahmed Mohammadin",
            "talabatId": "2825205",
            "keetaId": "",
            "zone": "Al karama",
            "bike": "55707 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "542201168",
            "email": "manal.yb55707@gmail.com",
            "joiningDate": "03-15-2025",
            "status": "active"
        },
        {
            "id": 23,
            "name": "Hasham Ramadan Atia Elsayed",
            "talabatId": "2843689",
            "keetaId": "",
            "zone": "Al barsha 1",
            "bike": "55104 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "503747986",
            "email": "hasham.yb55104@gmail.com",
            "joiningDate": "03-27-2025",
            "status": "active"
        },
        {
            "id": 24,
            "name": "Ahmed Mohamed Abdelmoneim Abdelal Bassiouny",
            "talabatId": "2843722",
            "keetaId": "",
            "zone": "Al nahda",
            "bike": "54946 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "504081578",
            "email": "abdelmoneim.yb54946@gmail.com",
            "joiningDate": "03-27-2025",
            "status": "active"
        },
        {
            "id": 25,
            "name": "Hassan Mohamed Ahmed Ahmed Rashed",
            "talabatId": "2843687",
            "keetaId": "",
            "zone": "Al barsha 1",
            "bike": "55967 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "504086928",
            "email": "rashed.yb55967@gmail.com",
            "joiningDate": "03-27-2025",
            "status": "active"
        },
        {
            "id": 26,
            "name": "Belal Ahmed Mohamed Abdelaziz Elkhouly",
            "talabatId": "2843685",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55635 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "504081488",
            "email": "belal.yb55635@gmail.com",
            "joiningDate": "03-27-2025",
            "status": "offboarded"
        },
        {
            "id": 27,
            "name": "Moataz Mohamed Mohamed Hassan Zithar",
            "talabatId": "2843684",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55427 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "542201156",
            "email": "moataz.yb55427@gmail.com",
            "joiningDate": "03-27-2025",
            "status": "offboarded"
        },
        {
            "id": 28,
            "name": "Mohamed Ahmed Elsayed Mohamed Elsabbagh",
            "talabatId": "2843681",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55704 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "503748975",
            "email": "elsayed.yb55704@gmail.com",
            "joiningDate": "03-27-2025",
            "status": "active"
        },
        {
            "id": 29,
            "name": "Mohamed Fouad Mahmoud Abdelgawad",
            "talabatId": "3492118",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55709 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508682128",
            "email": "fouad.yb55709@gmail.com",
            "joiningDate": "04-18-2025",
            "status": "offboarded"
        },
        {
            "id": 30,
            "name": "Abdelmaaboud Dahi Hosni Gadelkarim",
            "talabatId": "3492110",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55705 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "542201162",
            "email": "abdelmaaboud.yb55705@gmail.com",
            "joiningDate": "04-18-2025",
            "status": "offboarded"
        },
        {
            "id": 31,
            "name": "Abdellatif Hesham Abdellatif Elghareib Elgyar",
            "talabatId": "3492106",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55102 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "504081579",
            "email": "abdellatif.yb55102@gmail.com",
            "joiningDate": "04-18-2025",
            "status": "offboarded"
        },
        {
            "id": 32,
            "name": "Mohamed Elsayed Mostafa Elkady",
            "talabatId": "3492099",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55637 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "504081360",
            "email": "elkady.yb55637@gmail.com",
            "joiningDate": "04-18-2025",
            "status": "offboarded"
        },
        {
            "id": 33,
            "name": "Ahmed Maher Moustafa Hussein",
            "talabatId": "3492091",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55430 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "542201148",
            "email": "maher.yb55430@gmail.com",
            "joiningDate": "04-18-2025",
            "status": "offboarded"
        },
        {
            "id": 34,
            "name": "Ahmed Ragab Ahmed Mohamed",
            "talabatId": "3492087",
            "keetaId": "1758890619554758",
            "zone": "Unknown",
            "bike": "55434 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508682586",
            "email": "ragab.yb55434@gmail.com",
            "joiningDate": "04-18-2025",
            "status": "keeta"
        },
        {
            "id": 35,
            "name": "Mohamed Metwaly Mohamed Hussein Elsayed",
            "talabatId": "3492082",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55103 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "542201152",
            "email": "metwaly.yb55103@gmail.com",
            "joiningDate": "04-18-2025",
            "status": "active"
        },
        {
            "id": 36,
            "name": "Amr Gaber Adel Mohamed Hamdy Elmaghrby",
            "talabatId": "3504812",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55645 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "542201153",
            "email": "amr.yb55645@gmail.com",
            "joiningDate": "04-26-2025",
            "status": "offboarded"
        },
        {
            "id": 37,
            "name": "Mohamed Abdelhamid Gouda Salem",
            "talabatId": "3504809",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55636 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "503747183",
            "email": "gouda.yb55636@gmail.com",
            "joiningDate": "04-26-2025",
            "status": "offboarded"
        },
        {
            "id": 38,
            "name": "Ershad Alam Mahtab Alam",
            "talabatId": "3504743",
            "keetaId": "",
            "zone": "Business bay",
            "bike": "54944 DXB 2",
            "nationality": "Indian",
            "cPhone": "508463245",
            "email": "ershad.yb54944@gmail.com",
            "joiningDate": "04-26-2025",
            "status": "active"
        },
        {
            "id": 39,
            "name": "Gharib Said Gharib Mohamed Ali",
            "talabatId": "3527444",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55638 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508681630",
            "email": "gharib.yb55638@gmail.com",
            "joiningDate": "05-09-2025",
            "status": "active"
        },
        {
            "id": 40,
            "name": "Hassan Fathi Rabie Abdellatif",
            "talabatId": "3527440",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55432 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508682456",
            "email": "fathi.yb55432@gmail.com",
            "joiningDate": "05-09-2025",
            "status": "offboarded"
        },
        {
            "id": 41,
            "name": "Mohamed Hesham Saber Hamed Farag",
            "talabatId": "3527434",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55710 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "504089506",
            "email": "saber.yb55710@gmail.com",
            "joiningDate": "05-09-2025",
            "status": "offboarded"
        },
        {
            "id": 42,
            "name": "Mahmoud Mohamed Mohamed Elsaid Eeed",
            "talabatId": "3527429",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55708 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "503748850",
            "email": "mahmoud.yb55708@gmail.com",
            "joiningDate": "05-09-2025",
            "status": "offboarded"
        },
        {
            "id": 43,
            "name": "Mohamed Reda Mohamed Ismail Mohamed",
            "talabatId": "3663887",
            "keetaId": "1757676905514571",
            "zone": "Unknown",
            "bike": "55639 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "503747428",
            "email": "reda.yb55639@gmail.com",
            "joiningDate": "05-13-2025",
            "status": "offboarded"
        },
        {
            "id": 44,
            "name": "Maged Eid Mohamed Aly Eissa",
            "talabatId": "3663882",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55423 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "503747582",
            "email": "maged.yb55423@gmail.com",
            "joiningDate": "05-13-2025",
            "status": "active"
        },
        {
            "id": 45,
            "name": "Sushil Tamang",
            "talabatId": "1679979",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55431 DXB 2",
            "nationality": "Nepal",
            "cPhone": "508462790",
            "email": "sushil.yb55431@gmail.com",
            "joiningDate": "05-13-2025",
            "status": "active"
        },
        {
            "id": 46,
            "name": "Omar Hosny Abdelnaby Ali",
            "talabatId": "3672060",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55646 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508462571",
            "email": "omar.yb55646@gmail.com",
            "joiningDate": "05-16-2025",
            "status": "active"
        },
        {
            "id": 47,
            "name": "Mohamed Gamal Abdalla Abdelaal",
            "talabatId": "3682493",
            "keetaId": "1758889855518153",
            "zone": "Al karama",
            "bike": "55098 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508463430",
            "email": "gamal.yb55098@gmail.com",
            "joiningDate": "05-20-2025",
            "status": "keeta"
        },
        {
            "id": 48,
            "name": "Mohamed Sultan Ahmed Khalaf Ahmed",
            "talabatId": "3682481",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55974 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "504081851",
            "email": "sultan.yb55974@gmail.com",
            "joiningDate": "05-20-2025",
            "status": "offboarded"
        },
        {
            "id": 49,
            "name": "Andro Naseh Elgamal Attallah Nosir",
            "talabatId": "3682469",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62582 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508463522",
            "email": "andro.yb62582@gmail.com",
            "joiningDate": "05-20-2025",
            "status": "offboarded"
        },
        {
            "id": 50,
            "name": "Mahmoud Abdelhakim Mahmoud Ahmed Elkrwashy",
            "talabatId": "3682422",
            "keetaId": "",
            "zone": "Al karama",
            "bike": "60823 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "503746753",
            "email": "abdelhakim.yb60823@gmail.com",
            "joiningDate": "05-20-2025",
            "status": "active"
        },
        {
            "id": 51,
            "name": "Mohamed Mohamed Elsaid Abdelmakssoud Elgamal",
            "talabatId": "3776304",
            "keetaId": "1758889096554598",
            "zone": "Unknown",
            "bike": "60822 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "504087019",
            "email": "elgamal.yb60822@gmail.com",
            "joiningDate": "05-26-2025",
            "status": "keeta"
        },
        {
            "id": 52,
            "name": "Ibrahim Mohamed Ibrahim Hussein",
            "talabatId": "3777061",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62586 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508681833",
            "email": "ibrahim.yb62586@gmail.com",
            "joiningDate": "05-26-2025",
            "status": "offboarded"
        },
        {
            "id": 53,
            "name": "Melvin Steven Dias Steven Dias",
            "talabatId": "3796893",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55709 DXB 2",
            "nationality": "Indian",
            "cPhone": "508466903",
            "email": "melvin.yb55709@gmail.com",
            "joiningDate": "06-17-2025",
            "status": "active"
        },
        {
            "id": 54,
            "name": "Mahmoud Ahmed Abdelhamid Abouyousef",
            "talabatId": "3838289",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55974 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "542201164",
            "email": "abdelhamid.yb55974@gmail.com",
            "joiningDate": "06-23-2025",
            "status": "active"
        },
        {
            "id": 55,
            "name": "Ahmed Samir Ahmed Mohamed Badawy",
            "talabatId": "3838277",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55708 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508472968",
            "email": "samir.yb55708@gmail.com",
            "joiningDate": "06-23-2025",
            "status": "active"
        },
        {
            "id": 56,
            "name": "Ahmed Gamil Mohamed Mahrous Eliwa",
            "talabatId": "3838270",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55636 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "503746817",
            "email": "gamil.yb55636@gmail.com",
            "joiningDate": "06-23-2025",
            "status": "active"
        },
        {
            "id": 57,
            "name": "Hossam Hassan Abrahim Hassan",
            "talabatId": "3860418",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55971 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508472899",
            "email": "hossam.yb55971@gmail.com",
            "joiningDate": "07-02-2025",
            "status": "active"
        },
        {
            "id": 58,
            "name": "Ahmed Elsaid Ahmed Hussein Ahmed",
            "talabatId": "3871678",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55102 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508469807",
            "email": "ahmed.yb55432@gmail.com",
            "joiningDate": "07-07-2025",
            "status": "active"
        },
        {
            "id": 59,
            "name": "Mahmoud Sayed Imam Abdelsalam",
            "talabatId": "2086583",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55705 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508463549",
            "email": "sayed.yb55705@gmail.com",
            "joiningDate": "07-15-2025",
            "status": "active"
        },
        {
            "id": 60,
            "name": "Galal Abdelaal Hassanin Sayed Ahmed",
            "talabatId": "2087153",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55635 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508465296",
            "email": "galal.yb55635@gmail.com",
            "joiningDate": "07-15-2025",
            "status": "active"
        },
        {
            "id": 61,
            "name": "Omar Hashem Abdelkawy Mohamed",
            "talabatId": "3890991",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62586 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508467531",
            "email": "omar.yb62586@gmail.com",
            "joiningDate": "07-15-2025",
            "status": "active"
        },
        {
            "id": 62,
            "name": "Mohammed Imran Mohammed Basheer",
            "talabatId": "2834803",
            "keetaId": "1758806562580423",
            "zone": "Unknown",
            "bike": "55101 DXB 2",
            "nationality": "Indian",
            "cPhone": "508682751",
            "email": "imran.yb55101@gmail.com",
            "joiningDate": "07-18-2025",
            "status": "keeta"
        },
        {
            "id": 63,
            "name": "Mohammed Mahmood Mohammed Ghouse",
            "talabatId": "2834797",
            "keetaId": "1758800311512135",
            "zone": "Unknown",
            "bike": "55427 DXB 2",
            "nationality": "Indian",
            "cPhone": "508465738",
            "email": "mohammed.yb55427@gmail.com",
            "joiningDate": "07-18-2025",
            "status": "keeta"
        },
        {
            "id": 64,
            "name": "Ziad Yasser Elnabawi Fadel Mohamed",
            "talabatId": "3900818",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55645 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508472643",
            "email": "ziad.yb55645@gmail.com",
            "joiningDate": "07-18-2025",
            "status": "active"
        },
        {
            "id": 65,
            "name": "Mohamed Said Elsayed Mohamed Elgendy",
            "talabatId": "3912179",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62582 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508463780",
            "email": "said.yb62582@gmail.com",
            "joiningDate": "07-23-2025",
            "status": "active"
        },
        {
            "id": 66,
            "name": "Islam Ashraf Selim Rezk",
            "talabatId": "3912173",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55430 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508463006",
            "email": "islam.yb55430@gmail.com",
            "joiningDate": "07-23-2025",
            "status": "active"
        },
        {
            "id": 67,
            "name": "Mohamed Maarouf Abdelghany Ahmed",
            "talabatId": "3912169",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62863 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508472987",
            "email": "maarouf.yb62863@gmail.com",
            "joiningDate": "07-23-2025",
            "status": "active"
        },
        {
            "id": 68,
            "name": "Ahmed Youssef Ahmed Mohamed",
            "talabatId": "3912162",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62581 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508466732",
            "email": "youssef.yb62581@gmail.com",
            "joiningDate": "07-23-2025",
            "status": "active"
        },
        {
            "id": 69,
            "name": "Khaled Hegazi Elmandouh Abdelgawad Younes",
            "talabatId": "3912152",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "60813 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508682096",
            "email": "khaled.yb60813@gmail.com",
            "joiningDate": "07-23-2025",
            "status": "active"
        },
        {
            "id": 70,
            "name": "Muhammad Imran Khan Sabir Ali",
            "talabatId": "1208804",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62851 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "508473268",
            "email": "imran.yb62851@gmail.com",
            "joiningDate": "07-30-2025",
            "status": "active"
        },
        {
            "id": 71,
            "name": "Muhammad Umar Fiaz",
            "talabatId": "1834228",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62852 DXB2",
            "nationality": "Pakistani",
            "cPhone": "508682809",
            "email": "umar.yb62852@gmail.com",
            "joiningDate": "07-30-2025",
            "status": "active"
        },
        {
            "id": 72,
            "name": "Ammar Nawaz Haq Nawaz",
            "talabatId": "1834225",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62859 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "508472521",
            "email": "ammar.yb62859@gmail.com",
            "joiningDate": "07-30-2025",
            "status": "active"
        },
        {
            "id": 73,
            "name": "Muhammad Shahzad Muhammad Aslam",
            "talabatId": "3927068",
            "keetaId": "1758804974580650",
            "zone": "Unknown",
            "bike": "55637 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "542007956",
            "email": "shahzad.yb55637@gmail.com",
            "joiningDate": "07-31-2025",
            "status": "keeta"
        },
        {
            "id": 74,
            "name": "Hassan Ibrahim Hassan Hassan Tal",
            "talabatId": "3989869",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62580 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "522394268",
            "email": "tal.yb62580@gmail.com",
            "joiningDate": "08-04-2025",
            "status": "active"
        },
        {
            "id": 75,
            "name": "Ahmed Samih Zaky Ibrahim",
            "talabatId": "3682456",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62857 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "522485153",
            "email": "samih.yb62857@gmail.com",
            "joiningDate": "08-04-2025",
            "status": "active"
        },
        {
            "id": 76,
            "name": "Mahmoud Ehab Mohamed Badr",
            "talabatId": "3989870",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "Electric Bicycle",
            "nationality": "EGYPT",
            "cPhone": "522641750",
            "email": "ehab.yb1994@gmail.com",
            "joiningDate": "08-04-2025",
            "status": "active"
        },
        {
            "id": 77,
            "name": "Mohamed Sobhi Ahmed Mohamed",
            "talabatId": "3990013",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "Electric Bicycle",
            "nationality": "EGYPT",
            "cPhone": "522630874",
            "email": "sobhi.yb1980@gmail.com",
            "joiningDate": "08-04-2025",
            "status": "active"
        },
        {
            "id": 78,
            "name": "Mohamed Seddik Mohamed Seddik",
            "talabatId": "3989959",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "Electric Bicycle",
            "nationality": "EGYPT",
            "cPhone": "522516540",
            "email": "seddik.yb1996@gmail.com",
            "joiningDate": "08-04-2025",
            "status": "active"
        },
        {
            "id": 79,
            "name": "Mahmoud Mohamed Sayed Ahmed Eldeken",
            "talabatId": "3989957",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "Electric Bicycle",
            "nationality": "EGYPT",
            "cPhone": "521320555",
            "email": "eldeken.yb1988@gmail.com",
            "joiningDate": "08-04-2025",
            "status": "active"
        },
        {
            "id": 80,
            "name": "Tarek Salah Mohamed Abouarab Abdin Elkhatib",
            "talabatId": "3989958",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "Electric Bicycle",
            "nationality": "EGYPT",
            "cPhone": "521306222",
            "email": "tarek.yb1998@gmail.com",
            "joiningDate": "08-04-2025",
            "status": "active"
        },
        {
            "id": 81,
            "name": "Karim Mohamed Nabawy Elmalla",
            "talabatId": "3989867",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "Electric Bicycle",
            "nationality": "EGYPT",
            "cPhone": "521309888",
            "email": "karim.yb1989@gmail.com",
            "joiningDate": "08-04-2025",
            "status": "active"
        },
        {
            "id": 82,
            "name": "Abdul Rehman Muhammad Islam",
            "talabatId": "1834258",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "60819 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "508472835",
            "email": "abdulrehman.yb60819@gmail.com",
            "joiningDate": "08-06-2025",
            "status": "active"
        },
        {
            "id": 83,
            "name": "Muhammad Yasir Muhammad Jameel",
            "talabatId": "1224004",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55432 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "522719426",
            "email": "muhammadyasir.yb55432@gmail.com",
            "joiningDate": "08-06-2025",
            "status": "active"
        },
        {
            "id": 84,
            "name": "Muhammad Rashid Mahmood Muhammad Safdar Khan",
            "talabatId": "762216",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62849 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "522761353",
            "email": "muhammadrashid.yb62849@gmail.com",
            "joiningDate": "08-06-2025",
            "status": "active"
        },
        {
            "id": 85,
            "name": "Mahmoud Nadi Mahmoud Abdelaziz",
            "talabatId": "2203294",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62858 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "522476151",
            "email": "nadi.yb62858@gmail.com",
            "joiningDate": "08-06-2025",
            "status": "active"
        },
        {
            "id": 86,
            "name": "Amr Nasser Marei Ibrahim",
            "talabatId": "3522384",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "60818 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "522354658",
            "email": "amrnasser.yb60818@gmail.com",
            "joiningDate": "08-28-2025",
            "status": "active"
        },
        {
            "id": 87,
            "name": "Moaz Mohamed Abdelfattah Mahmoud Ali",
            "talabatId": "4007099",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "60825 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "521307999",
            "email": "moaz.yb60825@gmail.com",
            "joiningDate": "08-12-2025",
            "status": "active"
        },
        {
            "id": 88,
            "name": "Sherif Kamal Sonealla Aly Dwidar",
            "talabatId": "4007090",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "60815 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "521305666",
            "email": "sherif.yb60815@gmail.com",
            "joiningDate": "08-12-2025",
            "status": "active"
        },
        {
            "id": 89,
            "name": "Mohamed Khairy Refaiey Mohamed",
            "talabatId": "4007081",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "60814 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "521309666",
            "email": "khairy.yb60814@gmail.com",
            "joiningDate": "08-12-2025",
            "status": "active"
        },
        {
            "id": 90,
            "name": "Attiq Ur Rehman Muhammad Rafiq",
            "talabatId": "4012972",
            "keetaId": "1758806028593388",
            "zone": "Al barsha 1",
            "bike": "62850 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "521308666",
            "email": "attiq.yb62850@gmail.com",
            "joiningDate": "08-14-2025",
            "status": "keeta"
        },
        {
            "id": 91,
            "name": "Mahmoud Mohamed Hamdy Abdellatif Elwakil",
            "talabatId": "4012937",
            "keetaId": "",
            "zone": "Deira",
            "bike": "Electric Bicycle",
            "nationality": "EGYPT",
            "cPhone": "521302555",
            "email": "mahmoudelwakel360@gmail.com",
            "joiningDate": "08-14-2025",
            "status": "active"
        },
        {
            "id": 92,
            "name": "Abdelrahman Mabrouk Mansour Abdelsayed",
            "talabatId": "4016752",
            "keetaId": "",
            "zone": "Deira",
            "bike": "Electric Bicycle",
            "nationality": "EGYPT",
            "cPhone": "522714589",
            "email": "abdelrahmanmabrouk667@gmail.com",
            "joiningDate": "08-18-2025",
            "status": "active"
        },
        {
            "id": 93,
            "name": "Abdelhamid Mohamed Abdelhamid Ali",
            "talabatId": "4016735",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62865 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508472671",
            "email": "abdelhamid.yb62865@gmail.com",
            "joiningDate": "08-18-2025",
            "status": "active"
        },
        {
            "id": 94,
            "name": "Mohamed Osama Abdelhamid Abdelhamid",
            "talabatId": "4016725",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62846 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "522773168",
            "email": "osama.yb62846@gmail.com",
            "joiningDate": "08-18-2025",
            "status": "active"
        },
        {
            "id": 95,
            "name": "Amar Mohamed Abdulmajed Nagy Alshahawy",
            "talabatId": "4023037",
            "keetaId": "1759411061554930",
            "zone": "Deira",
            "bike": "62856 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "522803648",
            "email": "amar25elshahawy@gmail.com",
            "joiningDate": "08-21-2025",
            "status": "keeta"
        },
        {
            "id": 96,
            "name": "Ahmed Elsayed Mohamed Ahmed Fadl",
            "talabatId": "2203293",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62584 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "522076398",
            "email": "elsayed.yb62584@gmail.com",
            "joiningDate": "08-21-2025",
            "status": "active"
        },
        {
            "id": 97,
            "name": "Mohamed Salah Mohamed Selim Moussa",
            "talabatId": "4023026",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62844 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "522451189",
            "email": "salah.yb62844@gmail.com",
            "joiningDate": "08-21-2025",
            "status": "active"
        },
        {
            "id": 98,
            "name": "Mohamed Ahmed Mohamed Ali",
            "talabatId": "4023007",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62861 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "522681739",
            "email": "mohamedahmed.yb62861@gmail.com",
            "joiningDate": "08-21-2025",
            "status": "active"
        },
        {
            "id": 99,
            "name": "Abdelrahman Ahmed Mohamed Khalil",
            "talabatId": "4027950",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62860 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "522458712",
            "email": "abdelrahman.yb62860@gmail.com",
            "joiningDate": "08-25-2025",
            "status": "active"
        },
        {
            "id": 100,
            "name": "Abdelsalam Abdelnaser Kandil Abdelsalam Kandil",
            "talabatId": "4027935",
            "keetaId": "",
            "zone": "Al barsha 1",
            "bike": "Electric Bicycle",
            "nationality": "EGYPT",
            "cPhone": "522408119",
            "email": "abdelsalam.yb8119@gmail.com",
            "joiningDate": "08-25-2025",
            "status": "active"
        },
        {
            "id": 101,
            "name": "Elsayed Wageh Abdelbaset Elsayed Elmokly",
            "talabatId": "4034417",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "60810 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "522476731",
            "email": "elsayedwageh.yb6731@gmail.com",
            "joiningDate": "08-27-2025",
            "status": "active"
        },
        {
            "id": 102,
            "name": "Gomaa Lotfy Abdelrady Ibrahim",
            "talabatId": "4038340",
            "keetaId": "1762275702554227",
            "zone": "Unknown",
            "bike": "62857 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "522532917",
            "email": "gomaa.yb32917@gmail.com",
            "joiningDate": "08-29-2025",
            "status": "active"
        },
        {
            "id": 103,
            "name": "Ahmed Abdelhamid Mohamed Shamseldin",
            "talabatId": "4045093",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "60817 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "522178504",
            "email": "ahmed.yb60817@gmail.com",
            "joiningDate": "09-02-2025",
            "status": "active"
        },
        {
            "id": 104,
            "name": "Mostafa Mahmoud Sayed Ahmed Elsenousy",
            "talabatId": "4045190",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "60820 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "521729158",
            "email": "mostafa.yb94627@gmail.com",
            "joiningDate": "09-02-2025",
            "status": "active"
        },
        {
            "id": 105,
            "name": "Mukhtiar Ahmad Abdul Hameed",
            "talabatId": "829390",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "60828 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "522649953",
            "email": "mukhtiar.yb60828@gmail.com",
            "joiningDate": "09-15-2025",
            "status": "active"
        },
        {
            "id": 106,
            "name": "Mirza Inayathulla Baig Mirza Zafarulla Baig",
            "talabatId": "",
            "keetaId": "1757678974593004",
            "zone": "Unknown",
            "bike": "62583 DXB 2",
            "nationality": "Indian",
            "cPhone": "522845698",
            "email": "inayathulla.yb62583@gmail.com",
            "joiningDate": "09-12-2025",
            "status": "active"
        },
        {
            "id": 107,
            "name": "Usman Ahmad Razzaq Ahmad",
            "talabatId": "",
            "keetaId": "1757680265593816",
            "zone": "Unknown",
            "bike": "62864 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "521951836",
            "email": "usman.yb62864@gmail.com",
            "joiningDate": "09-12-2025",
            "status": "active"
        },
        {
            "id": 108,
            "name": "Ahmed Fathi Elsaid Abdelaziz Elnashar",
            "talabatId": "",
            "keetaId": "1758888283580359",
            "zone": "Unknown",
            "bike": "62587 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "542201140",
            "email": "ahmedfathi.yb62587@gmail.com",
            "joiningDate": "26-09-2025",
            "status": "active"
        },
        {
            "id": 109,
            "name": "Mohamed Ali Mohamed Ali",
            "talabatId": "",
            "keetaId": "1760466804514280",
            "zone": "Unknown",
            "bike": "60821 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "542201154",
            "email": "mohamedali.yb60821@gmail.com",
            "joiningDate": "14-10-2025",
            "status": "active"
        },
        {
            "id": 110,
            "name": "Ahsan Ul Haq Liaqat Ali",
            "talabatId": "1932441",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55098 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "508464973",
            "email": "ahsan.yb55098@gmail.com",
            "joiningDate": "17-10-2025",
            "status": "active"
        },
        {
            "id": 111,
            "name": "Ghulam Murtaza Muhammad Yaqoob",
            "talabatId": "1933201",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55970 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "508681899",
            "email": "ghulam.yb55970@gmail.com",
            "joiningDate": "17-10-2025",
            "status": "active"
        },
        {
            "id": 112,
            "name": "Ahmed Sabri Fekri Ahmed",
            "talabatId": "",
            "keetaId": "1760640709545530",
            "zone": "Unknown",
            "bike": "60822 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "504089110",
            "email": "",
            "joiningDate": "20-10-2025",
            "status": "active"
        },
        {
            "id": 113,
            "name": "Ibrahim Ibrahim Abdelfattah Ibrahim Ismail",
            "talabatId": "4203732",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "60824 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508472426",
            "email": "ibrahim.yb60824@gmail.com",
            "joiningDate": "20-10-2025",
            "status": "active"
        },
        {
            "id": 114,
            "name": "Ahmed Mohamed Fathy Elsemelawy",
            "talabatId": "",
            "keetaId": "1760790007545090",
            "zone": "Unknown",
            "bike": "55094 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "542201180",
            "email": "",
            "joiningDate": "20-10-2025",
            "status": "active"
        },
        {
            "id": 115,
            "name": "Ahmed Mohamed Abdelaziz Elsayed Ahmed Elsemelawy",
            "talabatId": "",
            "keetaId": "1760791043593880",
            "zone": "Unknown",
            "bike": "53892 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508462571",
            "email": "",
            "joiningDate": "20-10-2025",
            "status": "active"
        },
        {
            "id": 116,
            "name": "Mahmoud Tarek Mahrous Hassaballah",
            "talabatId": "4210735",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62579 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "521305222",
            "email": "tarek.yb62579@gmail.com",
            "joiningDate": "25-10-2025",
            "status": "active"
        },
        {
            "id": 117,
            "name": "Mahmoud Mohamed Hamdy Abdellatif Elwakil",
            "talabatId": "",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62866 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "521302555",
            "email": "",
            "joiningDate": "25-10-2025",
            "status": "active"
        },
        {
            "id": 118,
            "name": "Ahmed Abdelwahab Moursi Abdelwahab Khater",
            "talabatId": "",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "55706 DXB 2",
            "nationality": "EGYPT",
            "cPhone": "508464189",
            "email": "",
            "joiningDate": "26-10-2025",
            "status": "active"
        },
        {
            "id": 119,
            "name": "Ajinkya Jalindar Kamble Jalindar Sukhdeo Kamble",
            "talabatId": "",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "60827 DXB 2",
            "nationality": "Indian",
            "cPhone": "522097636",
            "email": "",
            "joiningDate": "04-11-2025",
            "status": "active"
        },
        {
            "id": 120,
            "name": "Waseem Nawaz Rabnawaz",
            "talabatId": "",
            "keetaId": "",
            "zone": "Unknown",
            "bike": "62854 DXB 2",
            "nationality": "Pakistani",
            "cPhone": "504081974",
            "email": "",
            "joiningDate": "04-11-2025",
            "status": "active"
        }
    ],
    
    offboarding: [
        { name: "Hassan Fathi Rabie Abdellatif", date: "10-14-2025", reason: "Termination" },
        { name: "Mohamed Reda Mohamed Ismail Mohamed", date: "09-04-2025", reason: "Termination" },
        { name: "Husnain Bahadar Khan", date: "09-04-2025", reason: "Termination" },
        { name: "Ibrahim Mohamed Ibrahim Hussein", date: "08-08-2025", reason: "Termination" },
        { name: "Hassan Nabil Hassan Mohamed Fekry", date: "08-01-2025", reason: "Resignation" },
        { name: "Ahmed Maher Moustafa Hussein", date: "08-01-2025", reason: "Resignation" },
        { name: "Belal Ahmed Mohamed Abdelaziz", date: "07-23-2025", reason: "Resignation" },
        { name: "Mohamed Abdelhamid Gouda Salem", date: "06-30-2025", reason: "Resignation" },
        { name: "Muhammad Muneeb Ur Rehman", date: "06-10-2025", reason: "Termination" }
    ],
    
    newHiring: [
        { name: "Mirza Inayathulla Baig", phone: "52 357 4621", date: "21-08-2025" },
        { name: "Mukhtiar Ahmad Abdul Hameed", phone: "52 169 6327", date: "22-08-2025" }
    ]
};
