version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: yellowbox-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - mcp-network

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yellowbox-mcp-server
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "9090:9090" # Metrics port
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./serviceAccount.json:/app/serviceAccount.json:ro
    depends_on:
      - redis
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis-data:
    driver: local

networks:
  mcp-network:
    driver: bridge