name: Security Audit

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  dependency-audit:
    name: Dependency Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Run npm audit
        run: npm audit --production
        continue-on-error: true
      
      - name: Run npm audit fix (dry run)
        run: npm audit fix --dry-run --production
        continue-on-error: true

  code-scanning:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript
      
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  firebase-rules-check:
    name: Firebase Security Rules Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Check Firestore rules
        run: |
          echo "Checking for common security issues in Firestore rules..."
          
          # Check for overly permissive rules
          if grep -E "allow (read|write): if true" firestore.rules.production; then
            echo "❌ ERROR: Found overly permissive rules!"
            exit 1
          fi
          
          # Check for proper authentication checks
          if ! grep -q "request.auth != null" firestore.rules.production; then
            echo "⚠️  WARNING: No authentication checks found in rules"
          fi
          
          echo "✅ Basic security checks passed"

  license-check:
    name: License Compatibility Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Install license checker
        run: npm install -g license-checker
      
      - name: Check licenses
        run: |
          license-checker --production --summary --excludePrivatePackages > licenses.txt
          echo "License summary:"
          cat licenses.txt
          
          # Check for problematic licenses
          if grep -E "(GPL|AGPL|LGPL)" licenses.txt; then
            echo "⚠️  WARNING: Found copyleft licenses that may require attention"
          fi